language: php

php:
  - 7.0
  - 7.1

sudo: false

install:
  - composer install

script:
  - vendor/bin/phpcs --standard=psr2 src/
  - vendor/bin/phpunit

after_script:
  - |
    wget https://scrutinizer-ci.com/ocular.phar
    php ocular.phar code-coverage:upload --format=php-clover coverage.clover
